one = "ghostface"
two = "gza"
three = "rza"
four = "raekwon"
five = "cappadonna"
six = "ODB"
seven = "method man"

print "the leader of the wu is ", three," because he is the head"
print "the main lyricist is ", two, " which is short for genius"
print "the star is ", seven, "because of the charisma"
